### ISSUE TITLE
Long Lockpad?

### ISSUE THREAD

**Issue by ghost** [max246/usbhub-pcb#2]
Hi, I've reached your project and seems really interesting to me. I'm currently learning a lot about electronics and I can't find any info about the Long Lockpads that you include in both the schematic and PCB layout. I'd want to know what's its purpose in the project or if it is even mandatory for the circuit. Thank you!

**Comment by max246** [comment]
hey, do you have screenshot of what you are referring? I am not sure what is it :)

**Comment by ghost** [comment]
Yes! 
![Captura](https://user-images.githubusercontent.com/59321512/77000625-fb289200-6958-11ea-854d-6118b74cb52d.PNG)

**Comment by max246** [comment]
Oh I see, it wasnt label properly but this was the external power supply.
My usb hub was made to accept an external 5V when some hungry devices requiring more than what the normal USB can provide. 

Dont need to use it, but just handy to have more juice :)

**Comment by ghost** [comment]
Oh I see, thanks a lot!
